# Generated by Django 3.2 on 2021-04-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('is_employer', models.BooleanField(default=False)),
                ('is_employee', models.BooleanField(default=True)),
                ('position', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('national_id', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
